[root]
subvol_main = @
subvol_snapshots = @snapshots
mountpoint = /btrfsroot
dev = /dev/nvme0n1p2

[home]
subvol_main = @home
subvol_snapshots = @home_snapshots
mountpoint = /btrfsroot
dev = /dev/nvme0n1p2
cache_subvol_relpath = daniel/.cache
